add to string
shaohedu/leetcodeTest pull request #2
Opened 2021-06-29 14:51 UTC by shaohedu

2021-06-29 15:51 UTC, jpxthu commented on test/to_string_test.hpp
> +#include <iostream>
Add blank line. Reference: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes
```suggestion
#include <iostream>

```

2021-06-29 15:52 UTC, jpxthu commented on test/to_string_test.hpp
> +using namespace std;
```suggestion
using namespace std;

```

2021-06-29 16:02 UTC, jpxthu requested changes

2021-06-29 16:02 UTC, jpxthu commented on test/to_string_test.hpp
> +using namespace std;
Add blank line. Reference: https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

```suggestion
#include <iostream>

using namespace std;

```

2021-06-29 16:02 UTC, jpxthu commented on test/to_string_test.hpp
> +{
https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions

```suggestion
void toStringTest() {
```

2021-06-29 16:02 UTC, jpxthu commented on test/to_string_test.hpp
> +    cout<<palindrom<<" testl"<<endl;
https://google.github.io/styleguide/cppguide.html#Horizontal_Whitespace

```suggestion
    cin >> i;
    string palindrom = to_string(i);
    cout << palindrom << " testl" << endl;
```

2021-06-29 16:02 UTC, jpxthu commented on test/to_string_test.hpp
> +}
New line at the end of file is more friendly for `git diff` if someone add something behind.
```suggestion
}

```

2021-06-30 14:17 UTC, jpxthu requested changes
贵司是严格按照 Google C++ Style Guilde 执行的吗？缩进是 4 个空格吗？给 IDE 加一个格式检查的插件来帮助检查格式问题。

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +    if (x<0) return false;
Format

```suggestion
    if (x < 0) return false;
```

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +    while (i < Palindrome.size()/2) {
Usually `length` is recommended for `std::string`.
```suggestion
    while (i < Palindrome.length() / 2) {
```

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +    std::string Palindrome = std::to_string(x);
https://google.github.io/styleguide/cppguide.html#Variable_Names

```suggestion
    std::string palindrome = std::to_string(x);
```

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +    while (i < Palindrome.size()/2) {
I think for loop has better readability.

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +            i++;
```suggestion
        i++;
```

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +
Remove this line.

```suggestion
```

2021-06-30 14:17 UTC, jpxthu commented on test/main.cpp
> +#include "is_palindrome.hpp"
Sort them.

2021-06-30 14:17 UTC, jpxthu commented on test/is_palindrome.hpp
> +bool isPalindrome(int x) {
https://google.github.io/styleguide/cppguide.html#Function_Names

```suggestion
bool IsPalindrome(int x) {
```

2021-06-30 14:17 UTC, jpxthu commented on test/to_string_test.hpp
> +void toStringTest() {
https://google.github.io/styleguide/cppguide.html#Function_Names

```suggestion
void ToStringTest() {
```

2021-07-04 01:32 UTC, shaohedu commented on test/is_palindrome.hpp
> +    while (i < Palindrome.size()/2) {
为什么：
Both string::size and string::length are synonyms and return the exact same value.
https://www.cplusplus.com/reference/string/string/length/

2021-07-04 04:29 UTC, jpxthu commented on test/is_palindrome.hpp
> +    while (i < Palindrome.size()/2) {
就是个习惯问题，一般 string 我看到绝大多数地方都会用 length

2021-07-04 04:59 UTC, jpxthu approved these changes
LGTM with nit

2021-07-04 04:59 UTC, jpxthu commented on test/main.cpp
> +#include "int_to_string.hpp"
顺序还是不对

2021-07-04 04:59 UTC, jpxthu commented on test/romaToInt.hpp
> +    int RomanToInt(std::string s) {
没有必要不要用值传递

```suggestion
    int RomanToInt(const std::string& s) {
```

2021-07-04 04:59 UTC, jpxthu commented on test/romaToInt.hpp
> +                x = x - value : x = x + value;
格式

```suggestion
            (value < roma_[s[i + 1]]) && (i < s.length() - 1) ? 
                x = x - value : x = x + value;
```

也可以这么写：

```suggestion
            x = (value < roma_[s[i + 1]]) && (i < s.length() - 1) ? 
                x - value : x = x + value;
```

2021-07-04 05:04 UTC, merged

2021-07-04 14:34 UTC, shaohedu commented on test/main.cpp
> +#include "int_to_string.hpp"
没懂，什么顺序？